### ISSUE TITLE
Error in Step2 where i am unable to start after update the APIID

### ISSUE THREAD

**Issue by pnatraj** [googlecodelabs/chatbase-codelab-io-2017#2]
natswipro@gcpchatbase:~/chatbase/chatbase-codelab-io-2017$ npm start

> @cristiancavalli/chatbase-io2017@0.0.1 start /home/natswipro/chatbase/chatbase-codelab-io-2017
> node index.js

/home/natswipro/chatbase/chatbase-codelab-io-2017/node_modules/@google/chatbase/lib/MessageFactory.js:118
  newMessage (apiKey=null, userId=null) {
                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/natswipro/chatbase/chatbase-codelab-io-2017/node_modules/@google/chatbase/lib/ApplicationInterface.js:19:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.10.0-40-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! @cristiancavalli/chatbase-io2017@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @cristiancavalli/chatbase-io2017@0.0.1 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @cristiancavalli/chatbase-io2017 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @cristiancavalli/chatbase-io2017
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @cristiancavalli/chatbase-io2017
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/natswipro/chatbase/chatbase-codelab-io-2017/npm-debug.log
natswipro@gcpchatbase:~/chatbase/chatbase-codelab-io-2017$ npm bugs @cristiancavalli/chatbase-io2017
npm ERR! Linux 4.10.0-40-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "@cristiancavalli/chatbase-io2017"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Not found : @cristiancavalli/chatbase-io2017
npm ERR! 404 
npm ERR! 404  '@cristiancavalli/chatbase-io2017' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/natswipro/chatbase/chatbase-codelab-io-2017/npm-debug.log

**Comment by pnatraj** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'bugs',
1 verbose cli   '@cristiancavalli/chatbase-io2017' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly fetchPackageMetaData @cristiancavalli/chatbase-io2017
5 silly fetchNamedPackageData @cristiancavalli/chatbase-io2017
6 silly mapToRegistry name @cristiancavalli/chatbase-io2017
7 silly mapToRegistry scope (from package name) @cristiancavalli
8 verbose mapToRegistry no registry URL found in name for scope @cristiancavalli
9 silly mapToRegistry using default registry
10 silly mapToRegistry registry https://registry.npmjs.org/
11 silly mapToRegistry uri https://registry.npmjs.org/@cristiancavalli%2fchatbase-io2017
12 verbose request uri https://registry.npmjs.org/@cristiancavalli%2fchatbase-io2017
13 verbose request no auth needed
14 info attempt registry request try #1 at 2:50:49 PM
15 verbose request id c2cc57123c00a26d
16 http request GET https://registry.npmjs.org/@cristiancavalli%2fchatbase-io2017
17 http 404 https://registry.npmjs.org/@cristiancavalli%2fchatbase-io2017
18 verbose headers { 'content-type': 'application/json',
18 verbose headers   'cache-control': 'max-age=0',
18 verbose headers   'content-length': '21',
18 verbose headers   'accept-ranges': 'bytes',
18 verbose headers   date: 'Thu, 30 Nov 2017 14:50:49 GMT',
18 verbose headers   via: '1.1 varnish',
18 verbose headers   age: '0',
18 verbose headers   connection: 'keep-alive',
18 verbose headers   'x-served-by': 'cache-sea1043-SEA',
18 verbose headers   'x-cache': 'MISS',
18 verbose headers   'x-cache-hits': '0',
18 verbose headers   'x-timer': 'S1512053450.757083,VS0,VE116' }
19 silly get cb [ 404,
19 silly get   { 'content-type': 'application/json',
19 silly get     'cache-control': 'max-age=0',
19 silly get     'content-length': '21',
19 silly get     'accept-ranges': 'bytes',
19 silly get     date: 'Thu, 30 Nov 2017 14:50:49 GMT',
19 silly get     via: '1.1 varnish',
19 silly get     age: '0',
19 silly get     connection: 'keep-alive',
19 silly get     'x-served-by': 'cache-sea1043-SEA',
19 silly get     'x-cache': 'MISS',
19 silly get     'x-cache-hits': '0',
19 silly get     'x-timer': 'S1512053450.757083,VS0,VE116' } ]
20 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
20 silly fetchPackageMetaData     at Request.<anonymous> (/usr/share/npm/node_modules/request/request.js:1082:10)
20 silly fetchPackageMetaData     at emitOne (events.js:82:20)
20 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
20 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/share/npm/node_modules/request/request.js:1009:12)
20 silly fetchPackageMetaData  error for @cristiancavalli/chatbase-io2017 { [Error: Not found : @cristiancavalli/chatbase-io2017]
20 silly fetchPackageMetaData   pkgid: '@cristiancavalli/chatbase-io2017',
20 silly fetchPackageMetaData   statusCode: 404,
20 silly fetchPackageMetaData   code: 'E404' }
21 verbose stack Error: Not found : @cristiancavalli/chatbase-io2017
21 verbose stack     at makeError (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:264:12)
21 verbose stack     at CachingRegistryClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:252:14)
21 verbose stack     at Request._callback (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:172:14)
21 verbose stack     at Request.self.callback (/usr/share/npm/node_modules/request/request.js:198:22)
21 verbose stack     at emitTwo (events.js:87:13)
21 verbose stack     at Request.emit (events.js:172:7)
21 verbose stack     at Request.<anonymous> (/usr/share/npm/node_modules/request/request.js:1082:10)
21 verbose stack     at emitOne (events.js:82:20)
21 verbose stack     at Request.emit (events.js:169:7)
21 verbose stack     at IncomingMessage.<anonymous> (/usr/share/npm/node_modules/request/request.js:1009:12)
22 verbose statusCode 404
23 verbose pkgid @cristiancavalli/chatbase-io2017
24 verbose cwd /home/natswipro/chatbase/chatbase-codelab-io-2017
25 error Linux 4.10.0-40-generic
26 error argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "@cristiancavalli/chatbase-io2017"
27 error node v4.2.6
28 error npm  v3.5.2
29 error code E404
30 error 404 Not found : @cristiancavalli/chatbase-io2017
31 error 404
32 error 404 '@cristiancavalli/chatbase-io2017' is not in the npm registry.
33 error 404 You should bug the author to publish it (or use the name yourself!)
34 error 404 Note that you can also install from a
35 error 404 tarball, folder, http url, or git url.
36 verbose exit [ 1, true ]
